//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (pa *Post) DeepCopyInto(out *Post) {
	*out = *pa
	out.TypeMeta = pa.TypeMeta
	pa.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Post.
func (pa *Post) DeepCopy() *Post {
	if pa == nil {
		return nil
	}
	out := new(Post)
	pa.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (pa *Post) DeepCopyObject() runtime.Object {
	if c := pa.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (pal *PostList) DeepCopyInto(out *PostList) {
	*out = *pal
	out.TypeMeta = pal.TypeMeta
	pal.ListMeta.DeepCopyInto(&out.ListMeta)
	if pal.Items != nil {
		in, out := &pal.Items, &out.Items
		*out = make([]Post, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostList.
func (pal *PostList) DeepCopy() *PostList {
	if pal == nil {
		return nil
	}
	out := new(PostList)
	pal.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (pal *PostList) DeepCopyObject() runtime.Object {
	if c := pal.DeepCopy(); c != nil {
		return c
	}
	return nil
}
